//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//Generated using version %PRODUCTVERSION% of the NHibernate DSL Tool

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SysCEF.Model
{
	[Serializable]
	[DataContract]
	// ReSharper disable PartialTypeWithSinglePart
	public partial class Imovel
	// ReSharper restore PartialTypeWithSinglePart
	{
		#region Constructors

		partial void BeforeInitialized();
		partial void AfterInitialized();

		public Imovel()
		{
			BeforeInitialized();
			
			NomeCliente = @"";
			Endereco = @"";
			Complemento = @"";
			Bairro = @"";
			CEP = @"";
			IdentificacaoCliente = @"";
			
			AfterInitialized();
		}

		#endregion Constructors

		#region Private Fields

		#pragma warning disable 0169

		[DataMember]
		// ReSharper disable InconsistentNaming
		///<summary>Field to facilitate optimistic locking</summary>
		private int __Version;
		// ReSharper restore InconsistentNaming

		#pragma warning restore 0169

		#endregion Private Fields

		#region Properties

		[DataMember]
		public virtual int ImovelID { get; set; }

		[DataMember]
		public virtual string NomeCliente { get; set; }

		[DataMember]
		public virtual string Endereco { get; set; }

		[DataMember]
		public virtual int Numero { get; set; }

		[DataMember]
		public virtual string Complemento { get; set; }

		[DataMember]
		public virtual string Bairro { get; set; }

		[DataMember]
		public virtual string CEP { get; set; }

		[DataMember]
		public virtual string IdentificacaoCliente { get; set; }

		[DataMember]
		public virtual Cidade Cidade { get; set; }

		[DataMember]
		public virtual TipoLogradouro TipoLogradouro { get; set; }

		#endregion Properties

		#region Object Overrides

		public override bool Equals(object obj)
		{
			if (obj == null)
				return false;

			if (ReferenceEquals(this, obj))
				return true;

			if (GetType() != obj.GetType())
				return false;

			return ImovelID <= 0 ? false : ImovelID == ((Imovel) obj).ImovelID;
		}

		public override int GetHashCode()
		{
			if (ImovelID <= 0)
				return base.GetHashCode();

			//Use 37 as a multiplier as it is a relatively large prime number
			//which helps to avoid collisions in a hashed data structure
			return 37 * ImovelID;
		}

		#endregion Object Overrides

	}
}
